/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reportes;
import Clases.DatabaseConnection;
import Clases.userClass;
import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.RenderingHints;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.image.BufferedImage;
import java.sql.Statement;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import net.sf.dynamicreports.jasper.builder.JasperReportBuilder;
import net.sf.dynamicreports.report.builder.DynamicReports;
import net.sf.dynamicreports.report.builder.column.Columns;
import net.sf.dynamicreports.report.builder.component.Components;
import net.sf.dynamicreports.report.builder.datatype.DataTypes;
import net.sf.dynamicreports.report.constant.HorizontalAlignment;
import net.sf.dynamicreports.report.constant.PageOrientation;
import net.sf.dynamicreports.report.constant.PageType;
import net.sf.dynamicreports.report.exception.DRException;

import net.sf.dynamicreports.report.builder.style.StyleBuilder;
import net.sf.dynamicreports.report.constant.SplitType;
import net.sf.dynamicreports.report.constant.VerticalAlignment;
import net.sf.dynamicreports.report.datasource.DRDataSource;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;



/**
 *
 * @author Axel Reyes
 */


public class frmTiempoRespuesta extends javax.swing.JFrame {

    /**
     * Creates new form frmTiempoRespuesta
     */
    public frmTiempoRespuesta() {
        initComponents();
         cargarComboBox();
      cargarReporte();
         lbUsuario.setText(userClass.getUsername());
         FechaActual();
         configurarComboBox();
         setDefaultCloseOperation(DISPOSE_ON_CLOSE);

         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tReporte = new javax.swing.JTable();
        btnImprimir = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        cmbAno = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tReporte.setEnabled(false);
        jScrollPane1.setViewportView(tReporte);

        btnImprimir.setText("Crear Reporte");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N

        jLabel2.setText("Nombre :");

        jLabel3.setText("Fecha");

        lbUsuario.setText("jLabel4");

        labelFecha.setText("jLabel4");

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTitulo.setText("REPORTE DEL TIEMPO DE RESPUESTA DE PROVEEDORES");

        jLabel6.setText("Mes");

        cmbAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbAno.setToolTipText("");

        jLabel5.setText("Año");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblLogo)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(lbUsuario)
                        .addGap(325, 325, 325)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(labelFecha))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAno, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(178, 178, 178)
                .addComponent(btnImprimir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(labelFecha)
                            .addComponent(jLabel2)
                            .addComponent(lbUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
          try {
        // 1. Configurar el informe con hoja A4 (orientación vertical) y márgenes
        JasperReportBuilder report = DynamicReports.report();
        report.setPageFormat(PageType.A4, PageOrientation.PORTRAIT)
            .setPageMargin(DynamicReports.margin(20)); // Aumentar márgenes para mejor presentación

        // 2. Definir estilos
        StyleBuilder borderedStyle = DynamicReports.stl.style()
            .setBorder(DynamicReports.stl.pen1Point());

        StyleBuilder headerStyle = DynamicReports.stl.style(borderedStyle)
            .setHorizontalAlignment(HorizontalAlignment.CENTER)
            .setVerticalAlignment(VerticalAlignment.MIDDLE)
            .setBackgroundColor(new Color(230, 230, 230))
            .setFontSize(16) // Aumentar el tamaño de la fuente del encabezado
            .setBold(true)
            .setPadding(5);

        StyleBuilder infoStyle = DynamicReports.stl.style()
            .setFontSize(12) // Aumentar el tamaño de la fuente de la información
            .setBold(false)
            .setPadding(2);

        StyleBuilder cellStyle = DynamicReports.stl.style(borderedStyle)
            .setHorizontalAlignment(HorizontalAlignment.CENTER)
            .setVerticalAlignment(VerticalAlignment.MIDDLE)
            .setFontSize(14) // Aumentar el tamaño de la fuente de las celdas
            .setPadding(5);

        // 3. Crear un DRDataSource con los datos de la tabla
        DRDataSource dataSource = new DRDataSource(
           "ID ", "Proveedor","Mes", "Año", "promedio de días"
        );

        // Llenar el data source con los datos de la tabla
        for (int i = 0; i < tReporte.getRowCount(); i++) {
            dataSource.add(
                tReporte.getValueAt(i, 0).toString(),
                tReporte.getValueAt(i, 1).toString(),
                tReporte.getValueAt(i, 2).toString(),
                 tReporte.getValueAt(i, 3).toString(),
                 tReporte.getValueAt(i, 4).toString()
                
            );
        }
            String MES="";
        // 4. Crear un gráfico con JFreeChart
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int i = 0; i < tReporte.getRowCount(); i++) {
            String nombre = tReporte.getValueAt(i, 1).toString();
            int cantidad = Integer.parseInt(tReporte.getValueAt(i, 4).toString());
            dataset.addValue(cantidad, "promedio de días", nombre);
              MES = tReporte.getValueAt(1,2).toString();
        }

        // Crear el gráfico
        JFreeChart chart = ChartFactory.createBarChart(
            lbTitulo.getText() + " "+MES.toUpperCase(),// Título del gráfico
            "Proveedores", // Etiqueta del eje X
            "promedio de días", // Etiqueta del eje Y
            dataset // Dataset con los datos
        );

        // Mejorar la calidad del gráfico
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setRenderer(new BarRenderer());
        plot.setDomainGridlinesVisible(true);
        plot.setRangeGridlinesVisible(true);

        // Habilitar anti-aliasing
        chart.getRenderingHints().put(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Cambiar el color de las barras
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        Color colorBarras = Color.decode("#80CAA6");
        renderer.setSeriesPaint(0, colorBarras);

        // Aumentar el tamaño de las etiquetas del eje Y (Cantidad)
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setTickLabelFont(new Font("SansSerif", Font.PLAIN, 24)); // Tamaño de fuente más grande
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits()); // Asegurar que sean enteros

        // Aumentar el tamaño de las etiquetas del eje X (Nombre)
        CategoryAxis domainAxis = plot.getDomainAxis();
        domainAxis.setTickLabelFont(new Font("SansSerif", Font.PLAIN, 24)); // Aumentar el tamaño aquí
        domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_90); // Rotar etiquetas 90 grados

        // Aumentar el tamaño del título del gráfico
        chart.getTitle().setFont(new Font("SansSerif", Font.BOLD, 30)); // Tamaño de fuente más grande
        chart.getLegend().setItemFont(new Font("SansSerif", Font.PLAIN, 25));
        // Aumentar el tamaño de las etiquetas de los ejes
        plot.getDomainAxis().setLabelFont(new Font("SansSerif", Font.BOLD, 25)); // Eje X
        plot.getRangeAxis().setLabelFont(new Font("SansSerif", Font.BOLD, 25));  // Eje Y

        // Aumentar el tamaño de la imagen
        BufferedImage chartImage = chart.createBufferedImage(1200, 1200);

        // 5. Construir el encabezado con logo a la izquierda y datos a la derecha
        try {
            // Cargar la imagen del logo
            java.awt.image.BufferedImage logo = javax.imageio.ImageIO.read(
                getClass().getResourceAsStream("/imagenes/logo.jpg"));

            // Encabezado (logo + datos de empresa, fecha, usuario)
            report.title(
                Components.horizontalList() // Contenedor horizontal
                .add(
                    // LOGO
                    Components.image(logo)
                    .setFixedDimension(80, 80) // Aumentar tamaño del logo
                    .setStyle(DynamicReports.stl.style().setPadding(10)),
                    Components.horizontalGap(20), // Espacio entre logo y texto
                    // Bloque vertical con la info (Empresa, Fecha, Usuario)
                    Components.verticalList(

                            Components.text("                                                                                                                                                                            "
                                + "Empresa: SuperMercado Abigail"+"                          Fecha: " + labelFecha.getText())
                            .setStyle(infoStyle),
                            Components.text("Usuario: " + lbUsuario.getText())
                            .setStyle(infoStyle)
                        )
                )
                // Opcional: bordes alrededor de la sección de encabezado
                .setStyle(DynamicReports.stl.style().setBorder(DynamicReports.stl.penThin()))
            );

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar el logo: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }

        // 6. Título principal centrado debajo del encabezado
        report.title(
            Components.verticalGap(10),
            Components.text(lbTitulo.getText()+" "+cmbMes.getSelectedItem().toString().toUpperCase()+" "+ cmbAno.getSelectedItem().toString())
                .setStyle(DynamicReports.stl.style()
                    .setFontSize(20) // Aumentar el tamaño de la fuente del título
                    .setBold(true)
                    .setForegroundColor(new Color(0, 0, 0)))
                .setHorizontalAlignment(HorizontalAlignment.CENTER),
            Components.verticalGap(20),
            Components.line().setPen(DynamicReports.stl.pen1Point()),
            Components.image(chartImage)
                .setFixedDimension(555, 450)
                .setHorizontalAlignment(HorizontalAlignment.CENTER),
            Components.pageBreak()
        );

        // 7. Definir las columnas de la tabla
        String[] columnNames = {"ID ", "Proveedor","Mes", "Año", "promedio de días"};
        int[] columnWidths = {80, 145, 80, 105, 100};

        for (int i = 0; i < columnNames.length; i++) {
            report.addColumn(
                Columns.column(columnNames[i], columnNames[i], DataTypes.stringType())
                    .setFixedWidth(columnWidths[i])
                    .setStyle(cellStyle)
                    .setTitleStyle(headerStyle)
            );
        }

        // 8. Agregar la tabla al detalle
        report.setDataSource(dataSource);
        report.setDetailSplitType(SplitType.PREVENT);

        // 9. Pie de página con información de generación y número de página
       report.pageFooter(
              Components.horizontalList(
                  Components.pageNumber()
                      .setStyle(DynamicReports.stl.style()
                          .setFontSize(8)
                          .setHorizontalAlignment(HorizontalAlignment.RIGHT) // Alinea a la derecha
                      )
                    )
                );

        // 10. Mostrar el informe en el visor gráfico sin cerrar el programa
        report.show(false);

    } catch (DRException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnImprimirActionPerformed

   private void cargarReporte() {
    DefaultTableModel model = new DefaultTableModel(
        new Object[][] {}, // Datos vacíos inicialmente
        new String[] {     // Títulos de las columnas
            "ID ", 
            "Proveedor", 
            "Mes", 
            "Año", 
            "Promedio de días"
        });

    tReporte.setModel(model);
    model.setRowCount(0);

    // Obtener el valor seleccionado del ComboBox
    String mesSeleccionado = cmbMes.getSelectedItem().toString();
    String año = cmbAno.getSelectedItem().toString();
    // Llamada al procedimiento almacenado
    String sql = "{CALL sp_ReporteTiempoRespuestaProveedores(?,?)}"; // Usar CALL para ejecutar procedimientos almacenados

    try (Connection conn = DatabaseConnection.getConnection();
         CallableStatement cstmt = conn.prepareCall(sql)) {

        // Establecer los parámetros del procedimiento almacenado
        cstmt.setString(1, mesSeleccionado);  // @Mes (nombre del mes)
        cstmt.setString(2, año);
        // Ejecutar el procedimiento almacenado
        ResultSet rs = cstmt.executeQuery();

        // Procesar el ResultSet
        while (rs.next()) {
            int id = rs.getInt("id_proveedor");
            String nombre = rs.getString("nombre_proveedor");
            String mes = rs.getString("Mes");
            int anio = rs.getInt("Anio");
            int tiempo = rs.getInt("TiempoRespuestaPromedio");

            // Agregar los datos a la tabla
            model.addRow(new Object[]{id, nombre, mes, anio, tiempo});
        }
    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar el reporte: " + e.getMessage());
    }
}     
    
 
    
private void cargarComboBox() {
    // Cargar meses (nombres)
    String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", 
                      "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
    for (String mes : meses) {
        cmbMes.addItem(mes);
    }
    
    
    String sqlAnios = "SELECT DISTINCT año FROM vista_reporte_nc ORDER BY año ASC";
    try (Connection conn = DatabaseConnection.getConnection();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sqlAnios)) {

        while (rs.next()) {
            cmbAno.addItem(rs.getString("año"));
        }
    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar años: " + e.getMessage());
    }

}
       
private void FechaActual(){
              Date fechaActual = new Date();

        // Formatear la fecha
        SimpleDateFormat formatter = new SimpleDateFormat("EEEE, dd MMMM yyyy");
        String fechaFormateada = formatter.format(fechaActual);

        // Crear el JLabel con la fecha
         labelFecha.setText(fechaFormateada);
        }


private void configurarComboBox() {
    // Agregar un ItemListener a cmbCategoria
    cmbMes.addItemListener(new ItemListener() {
        @Override
        public void itemStateChanged(ItemEvent e) {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                cargarReporte();  
            }
        }
    });

      cmbAno.addItemListener(new ItemListener() {
        @Override
        public void itemStateChanged(ItemEvent e) {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                cargarReporte();  
            }
        }
    });
   
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTiempoRespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTiempoRespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTiempoRespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTiempoRespuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTiempoRespuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox<String> cmbAno;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTable tReporte;
    // End of variables declaration//GEN-END:variables
}
